### PR TITLE
Announcement: 1st of August

### PR DESCRIPTION
**Pull request by garbas**
**Do not merge this until all tasks are done and until everybody does +1 !!!**
- [x] new design
- [ ] first section (top of the page) show details of the nixcon(date, location, get your ticket button, a current status text)
- [x] second section (below first section) list sponsors with a button/link "Become a sponsor" (link to "mailto:conf@nixos.org")
- [x] Third section is Schedule (or initially we can also integrate google form to submit CfP)

did i miss anything?

### CODE REVIEW

**Comment by manpages** [comment]
I don't understand “new design” thing. Shouldn't that one be ticked in the checkbox already?
I guess it's for protocol, so here's my :+1: for the new design.

Regarding 

> did i miss anything?

If we're going with minimalist one-page approach then, I think that you didn't miss anything.
I'm ready to collaborate on 2–4, like create Google™ Form™, style the button and so on.

I'm also thinking about the following — if we have one-page design, nav-bar is basically useless,
so why don't we put date, location, and get a ticket button (?) there?

**Comment by manpages** [comment]
Talked to @garbas, I retract my :+1: on design, we've decided to go for having a landing page with the following principal design —

Principal design of the new landing page

When the user scrolls down, she sees standard paper-like (black-on-white) page.

**Comment by garbas** [comment]
@manpages throwing some more ideas, please dont hate me :P 
1. maybe that white line (from tower) could split window in 2 (below buttons) above text (date, location, ...)
2. we could introduce one (and only one) color which we can use to highlight really important things (like buy ticket button) ... i would chose purple (well purple from nixos logo)
3. i wonder if we can make nixos logo spin when you scroll down :) ... (maybe an idea for the future ... not now)

**Comment by manpages** [comment]
@garbas Right now I just implemented scroll-toggle.
And yes, I can make it spin, but I feel that it's really frustrating :)

**Comment by manpages** [comment]
If we really want a line between buttons and logo, I'd propose having two lines instead.

See how this —

Better

is better than that —

Worse

In the latter version the tower is just hanging in space, which is not nice, compositionally.

**Comment by manpages** [comment]
I'm calling it a night. What is done —
1. Flipping-on-scroll landing page, it scrolls down and up.

What doesn't wotk —
1. On stock Android the page displays incorrectly, it sticks to the left instead of being centered as on the desktop.
2. In Firefox, flipping JavaScript doesn't work (I didn't debug it yet).

Overall, I'd be really glad if someone competent in CSS magic would have a look at this, because I have no idea what did I do wrong.

Going to sleep now :(

**Comment by manpages** [comment]
As before, you can test live version of the page on https://manpages.github.io

**Comment by manpages** [comment]
I say we don't push version of the web-site with landing page just yet, just minimalistic design with buttons (which I may style if you wish).

Then, as we decide how should scroll behave (I think that continuous scroll is really-really stupid), we add the landing screen.

**Comment by pesterhazy** [comment]
Hi, just a quick note, on https://manpages.github.io/ in Chromium, scrolling does not work at all. When you use the mouse wheel, it just flickers and does not scroll; with the scroll bar it flickers and jumps.

This is Chromium 41.0.2272.89 (Developer Build)

A slightly older one I guess but one I got from Nix :)

**Comment by manpages** [comment]
I've moved from flipper to parallax. Poll shows that flipper was counterintuitive.
Even though I really hate parallax. Prototype implementation of parallax that works on desktops (see further) lives on my github.io site.

Besides, I have tested a lot of parallax websites that are implemented by professional web-designers on stock Android browser and those just don't work as expected.

I over time, I got several versions of the website that work on desktop but don't work on phones properly. I think that it is really stupid to go for shiny things, given that there is literally zero professional hipsters on our team. I can keep throwing hours of my time on trying to build a cross-browser responsive parallax, but it feels like a waste of time. 

Non-parallax continuous scrolling is outright bad design.

What should I do now and what's our plan with website update in general?

**Comment by garbas** [comment]
sorry guys had to file my tax reports yesterday, that took most of my time.

i'm actually not sure when did we mention any special scroll affect. all i suggested was that first section (header) is stretched over whole height. and in order to reach other areas you simple scroll (without mentioning of any special scrolling effect). i think we misunderstood each other.

i'm sorry if i caused energy to be wasted.

in cases when there is no time to make an agreement (like now) i'm going to ask that we both come up our own website idea in next 24h. then i think we can judge which website sends the message out better. i think we all want a good website, sadly we need it ... well .. tomorrow :)

@manpages i'll ping you on irc to keep you updated on my progress.

**Comment by manpages** [comment]
@garbas I think that what you propose isn't a good design. I'll make a branch `minimal` here this night and make the website that's based on initial paper-like implementation. I'll just make a first section to contain buttons and the second section to contain current text about the conference.

**Comment by garbas** [comment]
i've added new design and made sure with testing from @pesterhazy that links, form, ticket purchase works. we're ready to go live in 30min.

**Pull request merged**
